// 全局状态：尽量集中管理 UI 与数据状态
export const state = {
  serviceAddr: "",
  serviceConnected: false,
  serviceBusy: false,
  serviceProbeId: 0,
  serviceLastError: "",
  serviceLastErrorAt: 0,
  currentPage: "dashboard",
  accountList: [],
  usageList: [],
  apiKeyList: [],
  apiModelOptions: [],
  requestLogList: [],
  requestLogTodaySummary: {
    todayTokens: 0,
    cachedInputTokens: 0,
    reasoningOutputTokens: 0,
    estimatedCost: 0,
  },
  usageAggregateSummary: {
    primaryBucketCount: 0,
    primaryKnownCount: 0,
    primaryUnknownCount: 0,
    primaryRemainPercent: null,
    secondaryBucketCount: 0,
    secondaryKnownCount: 0,
    secondaryUnknownCount: 0,
    secondaryRemainPercent: null,
  },
  requestLogQuery: "",
  requestLogStatusFilter: "all",
  accountSearch: "",
  accountFilter: "all",
  accountGroupFilter: "all",
  accountPage: 1,
  accountPageSize: 5,
  accountPageItems: [],
  accountPageTotal: 0,
  accountPageLoaded: false,
  selectedAccountIds: new Set(),
  manualPreferredAccountId: "",
  currentUsageAccount: null,
  activeLoginId: null,
  autoRefreshTimer: null,
};
